function PageInfo(){function x(a){for(var b=[];a;)b.unshift(a),a=a.parentNode;return b}function u(a,b){var c;c=(c=document.location.href.match(/^.*?:\/\/(www\.)?(.*?)(\/|$)/))?c[2]:null;if(y[c]){var d=document.querySelector(y[c].container);if(d){var k=d.querySelectorAll(y[c].include);if(k&&0<k.length){var f=k[k.length-1].nextElementSibling;e=document.createElement("div");for(d=0;d<k.length;d++)e.appendChild(k[d]);f.parentNode.insertBefore(e,f)}}}if(!e&&z[c])for(d=0;d<z[c].length;d++){if(k=document.querySelector(z[c][d])){e=
k;q=e.getBoundingClientRect();break}}else if(-1!=S.indexOf(c)){c=document.getElementsByTagName("img");d=null;for(f=k=0;f<c.length;f++){var g=window.getComputedStyle(c[f]),h=g.width.replace(/[^0-9.-]/g,""),g=g.height.replace(/[^0-9.-]/g,""),h=h*g;if(!d||h>k)d=c[f],k=h}(e=d)&&(q=e.getBoundingClientRect())}!e&&l&&(e=document.querySelector(n[l].content),e&&""!=e.textContent.trim()||(e=document.createElement("div"),document.body.insertBefore(e,document.body.firstChild)),q=e.getBoundingClientRect());!e&&
(c=["jpeg","jpg","gif","png"],(d=document.location.href.replace(/^.*\.(\w+)$/,"$1"))&&-1!=c.indexOf(d)&&(k=document.querySelector("body > img")))&&(e=k,q=e.getBoundingClientRect());if(!e&&"frameset"==document.body.nodeName.toLowerCase()){A=!0;c=document.getElementsByTagName("frame");d=null;for(f=k=0;f<c.length;f++)c[f].width&&c[f].height&&(h=c[f].width*c[f].height,h>k&&(d=c[f],k=h));(c=d)&&c.contentDocument&&c.contentDocument.documentElement&&(B=c,e=c.contentDocument.documentElement,q=e.getBoundingClientRect())}if(!e&&
a&&a._elements&&a._elements.length){e=a._elements[0];if(1<a._elements.length)if(c=a._elements,c.length)if(1==c.length)e=c[0];else{d=x(c[0]);f=null;for(k=1;k<c.length;k++){f=x(c[k]);h=null;for(g=0;g<d.length;g++)if(d[g]===f[g])h=d[g];else break;f=h;d=x(f)}e=f}else e=null;e.nodeType===Node.TEXT_NODE&&(e=e.parentNode)}e||(e=document.body);C=!0;b()}function D(){!e||e.parentNode&&e.getBoundingClientRect&&0!=e.getBoundingClientRect().width||(e=null,E=[],r=[],C=!1);C?1048576<document.body.innerHTML.length?
(log.warn("Page over 1mb, skipping article detection."),u(null,m)):m():"function"==typeof initClearlyComponent__detect&&"function"==typeof initClearlyComponent__next?(window.ClearlyComponent__detect={callbacks:{finished:function(a){a&&a._html&&r.push(a._html);window.ClearlyComponent__next.start();u(a,m)}},window:window,document:document,jQuery:window.jQuery},window.ClearlyComponent__detect=initClearlyComponent__detect(window.ClearlyComponent__detect),window.ClearlyComponent__detect?(window.ClearlyComponent__next=
{callbacks:{newPageFound:function(a){r.push(a._html);E.push(a._elements[0]);s&&s(a._html,a._url,r.length)}},settings:{onCreateNextPagesContainerUseThisId:"evernoteClearlyNextContainer"},detectComponentInstance:window.ClearlyComponent__detect},window.ClearlyComponent__next=initClearlyComponent__next(window.ClearlyComponent__next),window.ClearlyComponent__next?(window.ClearlyComponent__next.createNextPagesContainer(),window.ClearlyComponent__detect.start()):(log.warn("failed to initiate clearly next component"),
u(null,m))):(log.warn("failed to initiate clearly detect component"),u(null,m))):(log.warn("Couldn't find clearly!"),u(null,m))}function F(a){m=a;J?D():l?D():(J=!0,Browser.sendToExtension({name:"injectScript",script:"clearly/js/detect.js"}))}function G(a,b){s=b;F(function(){a(e);s&&s(null,null,r.length)});if(e)return e}function K(){var a=v();t=[];if(a)for(var b=0;b<a.rangeCount;b++){var c=a.getRangeAt(b);t[b]=c}}function v(){var a=window.getSelection();if(a&&a.rangeCount&&!a.isCollapsed)return a;
for(var a=[],b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)a.push(b[c]);b=document.getElementsByTagName("frame");for(c=0;c<b.length;c++)a.push(b[c]);b=document.location.href.replace(/^(https?:\/\/.*?)\/.*/i,"$1").toLowerCase();for(c=0;c<a.length;c++)if(!a[c].src||a[c].src.toLowerCase().substr(0,b.length)===b){var d=a[c].contentDocument;if(d){if((d=d.getSelection())&&d.rangeCount&&!d.isCollapsed)return L=!0,B=a[c],d}else log.warn("iframe contained no Document object.")}return null}function T(){var a=
window.getSelection();a.removeAllRanges();for(var b=0;b<t.length;b++)a.addRange(t[b])}function p(a,b,c,d,e,f){if(a.nodeType==Node.TEXT_NODE)return d||!l?(a=U(a,e),f=f?GlobalUtils.removePunctuation(a.trim()).replace(/\s+/g," "):a.trim().replace(/\s+/g," ")," "===f||""===f?b:b+" "+f):b;var g=["script","noscript","style"];if(a.nodeType==Node.ELEMENT_NODE&&-1==g.indexOf(a.nodeName.toLowerCase())){if(/^evernote.+Tools$/.test(a.id))return b;for(g=0;g<a.childNodes.length;g++){if(l){var h;h=a.childNodes[g];
var m=n[l].bannedSubelements;h=m&&h.webkitMatchesSelector&&h.webkitMatchesSelector(m)?!0:!1;if(h)continue;h=n[l].allowedElements;h=a.webkitMatchesSelector&&a.webkitMatchesSelector(h)?!0:!1;b=h||d?e?p(a.childNodes[g],b,c,!0,e,f):p(a.childNodes[g],b,c,!0,a,f):p(a.childNodes[g],b,c,!1,null,f)}else b=p(a.childNodes[g],b,c,!1,null,f);if(b.length>c)break}}return b}function U(a,b){var c=a.textContent;if(l){var d;if("Baidu"==l){if(d=b.parentNode.parentNode.querySelector(".g"))d=d.textContent}else if("Yandex"==
l){if(d=b.querySelector(".b-serp2-item__title-link"))d=d.href}else d=b.href;if(d){var e={wikipedia:/(.*)[-|\u2013|\u2014]/,youtube:/(.*)[-|\u2013|\u2014]/,facebook:/(.*)\|/,wiktionary:/(.*)-\sWiktionary/,stumbleupon:/(.*)\|\sStumbleUpon\.com/},f;for(f in e)if(RegExp(f).test(d)){var g=e[f].exec(c);if(g)return b.setAttribute("sawdivider",!0),g[1];if(b.getAttribute("sawdivider"))return""}}if(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/.test(c))return c.replace(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/g,
" ");if(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/.test(c))return c.replace(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/g," ")}return c}function V(){var a=document.title;if(l)if(n[l].titleTrim)a=n[l].titleTrim(a);else var b=a.split(" - "),a=a.replace(" - "+b[b.length-1],"");return a}function M(){if(l&&document.querySelector(n[l].searchBox)){var a=document.querySelector(n[l].searchBox).value.trim();if(0<a.length)return a}return null}
function N(a,b){var c="",c=v();if(a)G(function(a){b(p(a,"",510,!1,null,!1))});else{if(c){var c=c.getRangeAt(0).cloneContents(),d=document.createElement("div");d.appendChild(c);c=p(d,"",5E3,!1,null,!0)}else c=e?p(e,"",5E3,!1,null,!0):p(document.body,"",5E3,!1,null,!0);return c=V()+" "+c}}function O(a,b,c,d){a=v();a={containsImages:W,documentWidth:X,documentHeight:Y,url:Z,selection:null!==a||0<t.length,selectionIsInFrame:L,documentLength:document.body.textContent.length,articleBoundingClientRect:q,
article:null!=e,recommendationText:N(!1),query:M(),searchEngine:l,favIconUrl:H,documentIsFrameset:A,pdf:P(),gmailThread:Q(),gmail:w()};b.sendToTab?d(a,!0):d(a,!1)}function $(a,b){"undefined"!=typeof Browser&&(b?Browser.sendToExtension({name:"simSearch_receivePageInfo",info:a}):Browser.sendToExtension({name:"popup_receivePageInfo",info:a}))}function aa(a,b,c){"undefined"!=typeof SAFARI&&SAFARI&&!a.sendToTab&&0<t.length&&null==v()&&T();F(function(c){O(c,a,b,$)})}function R(){"undefined"!=typeof Browser&&
Browser.sendToExtension({name:"popup_pageInfoReadyToGo",url:document.location.href})}function P(){if(document.querySelector("embed[type='application/pdf']"))return document.querySelector("embed[type='application/pdf']").src;if(/^https?:\/\/docs\.google\.com\/viewer\?url=.+/.test(document.location.href))for(var a=0;a<document.scripts.length;a++)if(/gviewApp\.setFileData/.test(document.scripts[a].innerText)){if(/mimeType.+application\/pdf/.test(document.scripts[a].innerText))return a=/^https?:\/\/docs\.google\.com\/viewer\?url=(.+)/.exec(document.location.href),
decodeURIComponent(a[1]);break}return null}function w(){return/^https:\/\/mail\.google\.com\/mail\//.test(document.location.href)?!0:!1}function Q(){return w()&&0<document.querySelectorAll("span > div > span > [src='images/cleardot.gif']").length?!0:!1}function ba(a,b,c){H=a.favIconUrl}function ca(a,b,c){"clearly/js/detect.js"==a.script?Browser.sendToExtension({name:"injectScript",script:"clearly/js/next.js"}):"clearly/js/next.js"==a.script&&D()}var m,s,z={"penny-arcade.com":["div.contentArea > div.comic > img"],
"aspicyperspective.com":["div.entry-content"],"thewirecutter.com":["div#content"],"katespade.com":["div#pdpMain"],"threadless.com":["section.product_section"],"yelp.com":["div#bizBox"],"flickr.com":["div#photo"],"instagr.am":["div.stage > div.stage-inner"],"stackoverflow.com":["div#mainbar"],"makeprojects.com":["div#guideMain"],"cookpad.com":["div#main #recipe"],"imgur.com":["div.image"],"smittenkitchen.com":["div.entry"],"allrecipes.com":["div#content-wrapper"],"qwantz.com":["img.comic"],"questionablecontent.net":["img#strip"],
"cad-comic.com":["div#content"],"twitter.com":[".permalink","div.content-main"],"blog.evernote.com":[".post"]},y={"blog.evernote.com":{container:"#page-wrap > section > article",include:"h2, .p-meta, .post-meta, .thumbnail, .art-content"},"kirei.biglobe.ne.jp":{container:"div#main",include:".recipeTitle, .recipeMain, #howTo"},"nomnompaleo.com":{container:"section article.text",include:"header, section"},"foodnetwork.com":{container:"#fn-w",include:".rcp-head, .tabnav, #recipe-lead, .w-inner, .body-text"}},
S=["xkcd.com"],n={Baidu:{regex:/^https?:\/\/([^.\/]+\.)?baidu\.(com|cn)\/s/i,content:"#container",searchBox:"input[name=wd]",allowedElements:"h3.t a[data-click], .f font[size='-1']",bannedSubelements:"span.g, .m, .c",titleTrim:function(a){var b=/(.+)_\u767E\u5EA6\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},Bing:{regex:/^https?:\/\/([^.\/]+\.)?bing\.com\/search/i,content:"#results_container, #b_results",searchBox:"input[name=q]",allowedElements:"div.sb_tlst a, div.sa_mc p, .b_algo h2 a, .b_algo .b_caption p"},
Daum:{regex:/^https?:\/\/search\.daum\.net\/search/i,content:"#mArticle .inner_article",searchBox:"input[name=q]",allowedElements:".coll_cont ul .wrap_tit a, .coll_cont ul .f_eb.desc",titleTrim:function(a){var b=/(.+)\s\u2013/;return b.test(a)?b.exec(a)[1]:a}},Google:{regex:GlobalUtils.buildGoogleRegEx(),content:"#rso",searchBox:"input[name=q][type=hidden]",allowedElements:"a.l, span.st",bannedSubelements:"span.f"},Naver:{regex:/^https?:\/\/search\.naver\.com\/search\.naver/i,content:"#content",searchBox:"input[name=query]",
allowedElements:".type01 dt a, .type01 dd:not(.txt_inline):not(.txt_block):not(.review):not([style*='display:none'])",titleTrim:function(a){var b=/(.+)\s\u003A/;return b.test(a)?b.exec(a)[1]:a}},Yahoo:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.com\/s(earch|\?)/i,content:"#main",searchBox:"input[name=p]",allowedElements:".yschttl.spt[id], .abstr"},YahooCN:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.cn\/s(earch|\?)/i,content:".content",searchBox:"input[name=q]",allowedElements:"h3.title a, .desc",titleTrim:function(a){var b=
/(.+)_\u7F51\u9875\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},YahooJP:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.co\.jp\/s(earch|\?)/i,content:"#WS2m ul",searchBox:"input[name=p]",allowedElements:"#WS2m .hd h3 a, #WS2m .bd p",bannedSubelements:"#WS2m .bd p.dlink",titleTrim:function(a){var b=/\u300C(.+)\u300D/;return b.test(a)?b.exec(a)[1]:a}},Yandex:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.com\/yandsearch/,content:".b-serp2-list.b-serp.i-bem.b-serp_js_inited.b-serp2-list_js_inited",searchBox:"input[name=text]",
allowedElements:".b-serp2-item__title-link, .b-serp2-item__text",bannedSubelements:".b-serp2-item__from",titleTrim:function(a){var b=/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}},YandexRU:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.ru\/yandsearch/,content:".b-serp-list",searchBox:"input[name=text]",allowedElements:".b-serp-item__wrapper .b-serp-item__title-link, .b-serp-item__text",bannedSubelements:".b-serp-item__from",titleTrim:function(a){var b=/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}}},
W=Boolean(0<document.getElementsByTagName("img").length),X=document.width,Y=document.height,Z=document.location.href,e=null,E=[],r=[],q=null,L=!1,A=!1,B=null,H=null,J=!1,C=!1,t=[],l=null,I;for(I in n)if(n[I].regex.test(document.location.href)){l=I;break}"undefined"!=typeof Browser?Browser.addMessageHandlers({getInfo:aa,content_ready_6_0_3:R,setFavIconUrl:ba,injectedScript:ca}):window.addEventListener("message",function(a){"getInfo"==a.data.name&&O(null,a.data,null,function(a){document.title=a.recommendationText})});
"undefined"!=typeof SAFARI&&SAFARI&&(window.addEventListener("mouseup",K),Browser.addKeyboardHandlers({"65 + 91":K}));R();this.getBiggestImage=function(a){G(function(b){b=b?b.querySelectorAll("img"):document.querySelectorAll("img");for(var c=0,d=0,e,f=0;f<b.length;f++){var g=b.item(f).width,h=b.item(f).height;g*h>d*c&&(c=h,d=g,e=b.item(f).src)}a({src:e,width:d,height:c})})};this.getDefaultArticle=G;this.getCanonicalUrl=function(){if(!w()){var a=document.querySelector("link[rel='canonical']");if(a)return a.href}return null};
this.getCleanArticle=function(a,b){s=b;F(function(){a(r)})};this.getAdditionalPages=function(a){return E};this.getSelection=v;this.getSelectionFrame=function(){return B};this.getPdfUrl=P;this.getRecommendationText=N;this.getSearchQuery=M;this.isGmail=w;this.isGmailThread=Q;this.__defineGetter__("documentIsFrameset",function(){return A});this.__defineGetter__("favIconUrl",function(){return H});Object.preventExtensions(this)}Object.preventExtensions(PageInfo);
