function ContentPreview(){function C(){e.parentNode||document.documentElement.appendChild(e);var a=window.getComputedStyle(e,""),b=parseInt(a.getPropertyValue("width")),a=parseInt(a.getPropertyValue("height"));b&&a&&(e.style.marginLeft=0-b/2+"px",e.style.marginTop=0-a/2+"px")}function D(a,b,c,g,f){var n={"http://localhost/favicon.ico":!0};a=a?GlobalUtils.escapeXML(a):Browser.i18n.getMessage("quickNote_untitledNote");var y,k,d=document.createElement("div");d.style.whiteSpace="nowrap";var e=document.createElement("div");
e.textContent=a;e.style.fontFamily="Helvetica, Arial, sans-serif";e.style.fontSize="14px";e.style.fontWeight="bold";e.style.color="#0C0C0C";e.style.overflowX="hidden";e.style.textOverflow="ellipsis";e.style.paddingBottom="9px";d.appendChild(e);a=document.createElement("div");a.style.borderTop="1px solid #D8D8D8";a.style.height="0px";a.style.width="100%";d.appendChild(a);var h=document.createElement("div"),l=document.createElement("img"),m=document.createElement("div");m.style.display="inline-block";
m.style.verticalAlign="top";m.style.margin="15px 0px 0px 0px";m.style.width="364px";d.appendChild(m);var p=document.createElement("div");p.style.fontFamily="Helvetica, Arial, sans-serif";p.style.fontSize="12px";p.style.color="#0C0C0C";p.style.display="block";m.appendChild(p);var r=document.createElement("img"),s=document.createElement("a");s.href=b;s.textContent=b;s.style.display="inline-block";s.style.textDecoration="none";s.style.whiteSpace="nowrap";s.style.overflow="hidden";s.style.textOverflow=
"ellipsis";s.style.color="#0C0C0C";s.style.width="345px";p.appendChild(s);b=document.createElement("div");""!=g.trim()&&(b.textContent=500>g.length?g:g.slice(0,500)+"...",b.style.fontFamily="Helvetica, Arial, sans-serif",b.style.fontSize="12px",b.style.color="#0C0C0C",b.style.display="block",b.style.whiteSpace="normal",b.style.marginTop="15px",b.style.maxHeight="154px",b.style.overflow="hidden",m.appendChild(b));pageInfo.getBiggestImage(function(a){y=!0;a.src&&(h.style.position="relative",h.style.display=
"inline-block",h.style.width="150px",h.style.height="150px",h.style.margin="15px 30px 0px 0px",h.style.overflow="hidden",150<a.height||150<a.width?(l.setAttribute("thumbnail",a.src),z=l,Browser.sendToExtension({name:"cropImage",height:a.height,url:a.src,width:a.width}),l.style.maxWidth="none",l.style.maxHeight="none"):l.src=a.src,l.width=Math.min(150,a.width),l.height=Math.min(150,a.height),h.appendChild(l),m.parentNode?d.insertBefore(h,m):d.appendChild(h));k&&f(d)});if(c&&!n[c.toLowerCase()])r.onload=
function(){k=!0;r.style.display="inline-block";r.style.border="none";r.style.width="16px";r.style.height="16px";r.style.padding="0px";r.style.margin="0px 8px -2px 0px";r.width="16";r.height="16";p.insertBefore(r,s);y&&f(d)},r.onerror=function(){k=!0;y&&f(d)},r.src=c;else if(k=!0,y)return d}function E(a,b,c){function g(a){e.innerHTML="";e.appendChild(a);C()}var f=document.title,n=document.location.href,d=pageInfo.favIconUrl;pageInfo.getRecommendationText(!0,function(a){if(a=D(f,n,d,a,g))e.innerHTML=
"",e.appendChild(a),C()});t();k.reset();k.gray()}function t(){k.reset();k.hide();e.parentNode&&e.parentNode.removeChild(e);u.parentNode&&u.parentNode.removeChild(u)}function F(){if(d){var a;void 0!==typeof pageInfo&&(a=pageInfo.getSelectionFrame());a?(k.revealStaticRect(k.expandRect({width:a.width,height:a.height,top:a.offsetTop,bottom:a.height+a.offsetTop,left:a.offsetLeft,right:a.width+a.offsetLeft},-9),a,!0),k.show()):k.outlineElement(d,!0,!0)}else log.warn("Couldn't find a preview element. We should switch to 'full page' mode.")}
function G(a,b,c){window.focus();t();d||void 0===typeof pageInfo?d?(F(),1<A&&k.setPageCount(A-1)):log.warn("Couldn't find a 'pageInfo' object."):d=pageInfo.getDefaultArticle(function(a){d=a;F()},function(a,b,c){A=c;1<c&&A&&k.setPageCount(c-1)})}function v(a,b){if(!a)return log.warn("Can't determine if 'null' is interesting (it's probably not)."),!1;if(a===window.document||""==a.textContent.trim()&&0===a.getElementsByTagName("img").length)return!1;var c=a.getBoundingClientRect();if(!c.width||!c.height)return!1;
c=getComputedStyle(a);return"hidden"===c.visibility||"none"===c.display||a.parentNode&&b.parentNode&&(a.parentNode==b||b.parentNode==a)&&H(a,b)?!1:!0}function H(a,b){var c=a.getBoundingClientRect(),g=b.getBoundingClientRect();if(c.bottom==g.bottom&&c.height==g.height&&c.left==g.left&&c.right==g.right&&c.top==g.top&&c.width==g.width||a.textContent===b.textContent&&a.getElementsByTagName("img").length===b.getElementsByTagName("img").length)return!1}function I(a){for(var b=0;b<a.children.length;b++){if(H(a.children[b],
a))return I(a.children[b]);if(v(a.children[b],a))return a.children[b]}return a}function J(){var a=document.body.scrollWidth,b=document.body.scrollHeight,a={bottom:b-4,top:4,left:4,right:a-4,width:a-8,height:b-8};t();k.reset();k.revealStaticRect(a,document.body);k.show()}function K(){var a=document.querySelector("#evernoteTooltip");a&&a.parentNode.removeChild(a);u.innerHTML="";a=document.createElement("script");a.id="evernoteGmailScript";a.innerText='window.postMessage({ name: "receiveGmailIk", baseUrl: window.GLOBALS[31], ik: window.GLOBALS[9] }, "*");document.body.removeChild(document.getElementById("evernoteGmailScript"));';
document.body.appendChild(a);var a=document.createElement("div"),b=document.createElement("div");b.id="subject";b.className="header";b.innerText=document.querySelector("h1 > span").innerText;var c=document.createElement("div");b.appendChild(c);a.appendChild(b);var c=document.querySelectorAll("table tr:first-child td:first-child span[email]"),g=[],b=document.createElement("div");b.className="contact";b.innerText=Browser.i18n.getMessage("sender")+": "+c.item(0).getAttribute("email");a.appendChild(b);
for(b=1;b<c.length;b++){var f=c.item(b).getAttribute("email");0>g.indexOf(f)&&f!=c.item(0).getAttribute("email")&&g.push(c.item(b).getAttribute("email"))}b=g.join(", ");0<b.length&&(c=document.createElement("div"),c.className="contact",c.innerText=Browser.i18n.getMessage("recipients")+": "+b,a.appendChild(c));c=document.querySelectorAll("[role='presentation'] td:first-child > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(2) > div");for(b=g=0;b<c.length;b++)if(c.item(b).querySelector("table")){if(0<
g){var n=document.createElement("div");n.className="divider";a.appendChild(n);n=document.createElement("div");n.className="collapsedCount dimmed";n.innerText=Browser.i18n.getMessage("olderMessages",[g]);a.appendChild(n);g=0}n=document.createElement("div");n.className="divider";a.appendChild(n);var d=f=null,e=null,n=null,m=!1,q=null,h=c.item(b).querySelector(".hi");if(h){var h=h.parentNode,l=!1;h.getBoundingClientRect().width||(l=!0);for(var h=h.cloneNode(!0),w=9==h.children.length,d=h.querySelectorAll("[role='button'] img"),
f=0;f<d.length;f++)for(var e=window.getMatchedCSSRules(d.item(f)),p=0;p<e.length;p++)if(/ellipsis/.test(e[p].cssText)){e=d.item(f).parentNode.parentNode;p=e.nextElementSibling;e.parentNode.removeChild(e);p.parentNode.removeChild(p);break}f=h.firstElementChild;d=f.firstElementChild.firstElementChild.firstElementChild.querySelector("span[email]");e=f.firstElementChild.firstElementChild.firstElementChild.querySelector("span[title]");for(f=h.children.length-1;1<=f;f--)if(h.children[f].textContent.trim()&&
(w&&f!=h.children.length-2||!w)){l?n=h.children[f].textContent.slice(0,77)+"...":(n=h.children[f].innerHTML,m=!0);break}if(w&&!l)for(h=h.children[h.children.length-2].querySelectorAll("table"),q=document.createDocumentFragment(),f=0;f<h.length;f++){l=document.createElement("div");w=document.createElement("span");p=document.createElement("span");p.className="dimmed";var r=h.item(f).querySelector("td:last-child b"),s=h.item(f).querySelector("td:last-child span").previousSibling,v=h.item(f).querySelector("td:last-child span a[download_url]");
w.textContent=r.textContent;p.textContent=" ("+s.textContent.trim()+")";l.setAttribute("evernote_attachment_url",v.href);l.setAttribute("evernote_attachment_name",r.textContent);l.style.display="block";l.appendChild(w);l.appendChild(p);q.appendChild(l)}}else h=c.item(b).querySelector("table[aria-role='presentation']"),f=h.firstElementChild.firstElementChild,d=f.children[0],e=f.children[2].querySelector("span[title]"),n=f.children[1].textContent;f=document.createElement("div");h=document.createElement("div");
l=document.createElement("span");l.className="header sender";l.innerText=d.textContent;h.appendChild(l);l=document.createElement("span");l.className="dimmed date";l.innerText=e.title;h.appendChild(l);f.appendChild(h);l=document.createElement("div");l.className="body";n&&(m?l.innerHTML=n:l.innerText=n);f.appendChild(l);q&&(l=document.createElement("div"),l.className="attachments",l.appendChild(q),f.appendChild(l));a.appendChild(f)}else g++;u.appendChild(a);t();k.reset();k.gray();u.parentNode||document.documentElement.appendChild(u)}
function L(a,b){var c={top:Math.min(a.top,b.top),bottom:Math.max(a.bottom,b.bottom),left:Math.min(a.left,b.left),right:Math.max(a.right,b.right)};c.width=c.right-c.left;c.height=c.bottom-c.top;return c}function O(a){if(0!==a.endOffset||a.endContainer.nodeType!==Node.ELEMENT_NODE)return a=a.getBoundingClientRect(),{top:a.top,bottom:a.bottom,left:a.left,right:a.right,width:a.width,height:a.height};var b=null;try{b=a.endContainer.getBoundingClientRect()}catch(c){log.warn("Couldn't get a bounding client rect for our end element, maybe it's a text node.")}for(var g=
!1,f=[],d=a.getClientRects(),e=0;e<d.length;e++)(b||d[e]?b&&d[e]&&b.top==d[e].top&&b.bottom==d[e].bottom&&b.left==d[e].left&&b.right==d[e].right&&b.width==d[e].width&&b.height==d[e].height:1)&&!g?g=!0:f.push(d[e]);if(0==f.length)return a.getBoundingClientRect();if(1==f.length)return f[0];a=f[0];for(e=1;e<f.length;e++)a=L(a,f[e]);return a}function M(a,b){var c=b,g=a.getBoundingClientRect(),g={bottom:g.bottom+window.scrollY,height:g.height,left:g.left+window.scrollX,right:g.right+window.scrollX,top:g.top+
window.scrollY,width:g.width};if("rtl"==document.dir||0>g.bottom&&0>g.top||0>g.left&&0>g.right)return c;var f=getComputedStyle(a);if("none"==f.display||"hidden"==f.overflowX||"hidden"==f.overflowY)return c;1<g.width*g.height&&(c=L(g,b));if(a.children)for(g=0;g<a.children.length;g++)c=M(a.children[g],c);return c}function N(){var a;if(void 0!==typeof pageInfo&&!m){a=pageInfo.getSelection();m=[];q=[];for(var b=0;b<a.rangeCount;b++)m.push(a.getRangeAt(b).cloneRange()),q.push([m[b].startOffset,m[b].endOffset]);
x=pageInfo.getSelectionFrame()}if(!a){a=window.getSelection();a.removeAllRanges();for(var c=0;c<m.length;c++){var g=document.createRange();if((m[c].startContainer.length||m[c].startContainer.children.length)<q[c][0])for(var f=0,b=0;b<m[c].startContainer.childNodes.length;b++){var d=m[c].startContainer.childNodes[b],e=0,e=d.getAttribute&&d.getAttribute("clearly_highlight_id")?(d.innerText||d.textContent).length:d.length||d.children.length,f=f+e;if(f>=q[c][0]){g.setStart(d,q[c][0]-(f-e));break}}else g.setStart(m[c].startContainer,
q[c][0]);if((m[c].endContainer.length||m[c].endContainer.children.length)<q[c][1])for(b=f=0;b<m[c].endContainer.childNodes.length;b++){if(d=m[c].endContainer.childNodes[b],e=d.getAttribute&&d.getAttribute("clearly_highlight_id")?(d.innerText||d.textContent).length:d.length||d.children.length,f+=e,f>=q[c][1]){g.setEnd(d,q[c][1]-(f-e));break}}else g.setEnd(m[c].endContainer,q[c][1]);a.addRange(g)}}return a}function B(){var a=N();k.reset();var b=null;x&&(b=x.getBoundingClientRect());var c,d;if(a)for(t(),
k.reset(),d=0;d<a.rangeCount;d++)c=a.getRangeAt(d),c=O(c),c.top+=document.body.scrollTop,c.bottom+=document.body.scrollTop,c.left+=document.body.scrollLeft,c.right+=document.body.scrollLeft,b&&(c.left+=b.left,c.right+=b.left,c.top+=b.top,c.bottom+=b.top),k.revealStaticRect(c,x,!1),k.show();k.show()}var k=new ContentVeil,d=null,A=0,m=null,q=null,x=null,e=function(){var a=document.createElement("div");a.id="evernotePreviewContainer";a.className="evernotePreviewContainer evernotePreviewUrlContainer";
return a}(),z,u=function(){var a=document.createElement("div");a.id="evernoteEmailPreview";return a}();Browser.addMessageHandlers({preview_clear:t,receiveCroppedImage:function(a,b,c){z&&(z.src=a.datauri,z.removeAttribute("thumbnail"))}});window.addEventListener("message",function(a){"previewArticle"==a.data.name?G():"previewFullPage"==a.data.name?J():"previewUrl"==a.data.name?E():"previewEmail"==a.data.name?K():"clearPreview"==a.data.name?t():"previewSelection"==a.data.name?B():"receiveGmailIk"==
a.data.name&&Browser.sendToExtension({name:"downloadGmailThread",baseUrl:a.data.baseUrl,ik:a.data.ik,threadId:window.location.href.split(/#.+?\//)[1]})});this.clear=t;this.getArticleElement=function(){return d};this.getUrlElement=function(a){function b(){var a=e.querySelector("[thumbnail]");a&&a.parentNode.parentNode.removeChild(a.parentNode);for(var a="",b=e.innerHTML.split(/(?=<img.[^>]+>)/),d=0;d<b.length;d++)a=/^<img/.test(b[d])?a+b[d].replace(/>/,"></img>"):a+b[d];return a}if(e.innerHTML)return b();
pageInfo.getRecommendationText(!0,function(c){if(c=D(document.title,document.location.href,pageInfo.favIconUrl,c,function(c){c&&(e.innerHTML="",e.appendChild(c),a(b()))}))e.innerHTML="",e.appendChild(c),a(b())})};this.looksInteresting=v;this.computeDescendantBoundingBox=function(a){if(!a)return{top:0,bottom:0,left:0,right:0,width:0,height:0};var b=a.getBoundingClientRect();return M(a,{bottom:b.bottom+window.scrollY,height:b.height,left:b.left+window.scrollX,right:b.right+window.scrollX,top:b.top+
window.scrollY,width:b.width})};this.getEmailElement=function(){return u};this.previewArticle=G;this.previewFullPage=J;this.previewSelection=B;this.ensureSelectionIsShown=N;this.previewUrl=E;this.previewEmail=K;this.expandPreview=function(){for(var a=d,b=d.parentNode;b;){if(v(b,d)){b.enNudgeDescendToNode=d;d=b;break}b=b.parentNode}a!==d&&k.outlineElement(d,!1,!0,!0)};this.contractPreview=function(){var a=d;if(d.enNudgeDescendToNode){var b=d.enNudgeDescendToNode;delete d.enNudgeDescendToNode;d=b}else d=
I(d);a!==d&&k.outlineElement(d,!1,!0,!0)};this.moveToElementAbove=function(){for(var a=d.previousElementSibling;a;){if(v(a,d)){d=a;k.outlineElement(d,!1,!0,!0);break}a=a.previousElementSibling}};this.moveToElementBelow=function(){for(var a=d.nextElementSibling;a;){if(v(a,d)){d=a;k.outlineElement(d,!1,!0,!0);break}a=a.nextElementSibling}};this.isPointOnVeil=function(a,b){var c=parseFloat(k.getElement().style.borderTopWidth),d=parseFloat(k.getElement().style.borderRightWidth),e=parseFloat(k.getElement().style.borderBottomWidth),
m=parseFloat(k.getElement().style.borderLeftWidth),q=parseFloat(k.getElement().style.width),t=parseFloat(k.getElement().style.height);return a<q-d&&a>m&&b>c&&b<t-e?!1:!0};this.reset=function(){x=q=m=null};this.gray=function(){t();k.reset();k.gray()};this.previewSelection=B;Object.preventExtensions(this)};
