if("undefined"==typeof Browser){var Browser={runIfInTopFrame:function(a){SAFARI?a():navigator.userAgent.match(/chrome/i)&&a()},messageListeners:[]},initBrowser=function(){Browser.i18n=chrome.i18n;Browser.extension=chrome.extension;Browser.runtime=chrome.runtime;Browser.EVERNOTE_VERSION="6.0.2";Browser.agent=null;Browser.keyCombos={};Browser.currentKeys={};Browser.currentPorts={};SAFARI||(chrome.runtime?chrome.runtime.onConnect.addListener(function(a){for(var b=0;b<Browser.messageListeners.length;b++)a.onMessage.addListener(Browser.messageListeners[b]);
a.onDisconnect.addListener(function(){Browser.currentPorts[a.portId_]&&delete Browser.currentPorts[a.portId_]});Browser.currentPorts[a.portId_]=a}):chrome.extension&&chrome.extension.onConnect.addListener(function(a){for(var b=0;b<Browser.messageListeners.length;b++)a.onMessage.addListener(Browser.messageListeners[b]);a.onDisconnect.addListener(function(){Browser.currentPorts[a.portId_]&&delete Browser.currentPorts[a.portId_]});Browser.currentPorts[a.portId_]=a}));Browser.sendToTab=function(a,b,c){if(SAFARI)try{a.page.dispatchMessage(b.name,
b)}catch(d){}else"undefined"!=typeof c&&Browser.currentPorts[c]?Browser.currentPorts[c].postMessage(b):chrome.tabs.sendMessage?chrome.tabs.sendMessage(a.id,b):chrome.tabs.sendRequest(a.id,b)};Browser.sendToExtension=function(a,b){SAFARI?safari.self.tab.dispatchMessage(a.name,a):"undefined"!=typeof b&&Browser.currentPorts[b]?Browser.currentPorts[b].postMessage(a):chrome.runtime?chrome.runtime.sendMessage(a):chrome.extension&&chrome.extension.sendMessage?chrome.extension.sendMessage(a):chrome.extension.sendRequest(a)};
Browser.openPort=function(a){if(!SAFARI){a||(a={});var b;/background\.html$/.test(document.location.href)?b=chrome.tabs.connect(a.tabId):chrome.runtime?b=chrome.runtime.connect():chrome.extension&&(b=chrome.extension.connect());a.messageHandlers&&b.onMessage.addListener(function(c){if(a.messageHandlers[c.name])a.messageHandlers[c.name](c,b)});Browser.currentPorts[b.portId_]=b;return b.portId_}};Browser.closePort=function(a){!SAFARI&&Browser.currentPorts[a]&&(Browser.currentPorts[a].disconnect(),delete Browser.currentPorts[a])};
Browser.getAgent=function(){if(Browser.agent)return Browser.agent;var a="Unknown/1.0",b=/^Mozilla\/\d+(\.\d+)*\s+\(.*?([^;()]*(Windows|OS X|Linux)[^;()]*).*?\)/i.exec(navigator.userAgent);b&&b[2]&&(a=b[2].trim());a=a.replace(/\s+(\S*\d)/,"/$1");a="Evernote Webclipper/"+Browser.EVERNOTE_VERSION+" ("+navigator.language+"); "+a+"; ";b="0.0";SAFARI?(b=navigator.userAgent.replace(/^.*Version\/([0-9.]+).*$/,"$1"),b==navigator.userAgent&&(b="0.0"),a+="Safari/"+b):(b=navigator.userAgent.replace(/^.*Chrome\/([0-9.]+).*$/,
"$1"),b==navigator.userAgent&&(b="0.0"),a+="Chrome/"+b);Browser.agent=a+";";return Browser.agent};Browser.removeMessageHandlers=function(){if(SAFARI)for(var a=null,a=safari.application?safari.application:safari.self,b=0;b<Browser.messageListeners.length;b++)a.removeEventListener("message",Browser.messageListeners[b],!1),console.log("Removing message listener: "),console.log(Browser.messageListeners[b]);Browser.messageListeners=[]};Browser.addMessageHandlers=function(a,b){var c;if(SAFARI){if("about:blank"==
document.location.href||!b&&window&&window.parent!=window&&(c=chrome.extension.getURL(""),document.location.href.substr(0,c.length)!=c))return;var d=null;if(!safari){log.warn("No 'safari' object.");return}d=safari.application?safari.application:safari.self;c=function(b){if(b.name&&a[b.name])a[b.name](b.message,{tab:b.target},null)};d.addEventListener("message",c,!1)}else c=function(b,c,d){if(!c||c.id!==chrome.i18n.getMessage("@@extension_id")&&c.sender&&c.sender.id!==chrome.i18n.getMessage("@@extension_id"))log.warn("Got request from unexpected sender. Ignoring.");
else{if(b.name&&a[b.name])a[b.name](b,c,d);if(d)return!0}},chrome.extension.onMessage?chrome.extension.onMessage.addListener(c):chrome.extension.onRequest.addListener(c);Browser.messageListeners.push(c)};Browser.addKeyboardHandlers=function(a){for(var b in a)Browser.keyCombos[b]=a[b]};Browser.handleKeys=function(){var a=[],b;for(b in Browser.currentKeys)a.push(parseInt(b));a.sort(function(a,b){return a-b});a=a.join(" + ");if(Browser.keyCombos[a])Browser.keyCombos[a](a);Browser.currentKeys={}};Browser.setIcon=
function(a){if(SAFARI)for(var b in safari.extension.toolbarItems){var c=safari.extension.toolbarItems[b];"clipper"==c.identifier&&(c.image=safari.extension.baseURI+a+"-16x16.png")}else chrome.browserAction.setIcon({path:{19:chrome.extension.getURL(a+"-19x19.png"),38:chrome.extension.getURL(a+"-19x19@2x.png")}})};Browser.setTitle=function(a){if(SAFARI)for(var b in safari.extension.toolbarItems){var c=safari.extension.toolbarItems[b];"clipper"==c.identifier&&(c.toolTip=a)}else chrome.browserAction.setTitle({title:a})};
Browser.setBrowserActionClickHandler=function(a){SAFARI?safari.application.addEventListener("command",function(b){if("clipper"==b.command){b=safari.extension.toolbarItems;for(var c=0;c<b.length;c++)if("clipper"==b[c].identifier){a();break}}}):chrome.browserAction.onClicked&&(chrome.browserAction.onClicked.hasListener(a)||chrome.browserAction.onClicked.addListener(a))};Browser.insertJS=function(a,b){SAFARI?(safari.extension.addContentScriptFromURL(safari.extension.baseURI+a),b&&b()):b?chrome.tabs.executeScript(null,
{file:a},b):chrome.tabs.executeScript(null,{file:a})};Browser.insertCSS=function(a,b){SAFARI?(safari.extension.addContentStyleSheetFromURL(safari.extension.baseURI+a),b&&b()):b?chrome.tabs.insertCSS(null,{file:a},b):chrome.tabs.insertCSS(null,{file:a})};Browser.captureVisibleTab=function(a,b,c){function d(d){c?c(d):Browser.sendToTab(b.tab,{name:"receiveScreenshot",url:d,tool:a.tool,showSubtools:a.showSubtools})}SAFARI?b.tab.visibleContentsAsDataURL(d):chrome.tabs.captureVisibleTab(b.tab.windowId,
{format:a.format||"png",quality:a.quality||1},d)};window.addEventListener("keydown",function(a){189==a.keyCode&&a.altKey?Browser.currentKeys[76]=a:188==a.keyCode&&a.altKey?Browser.currentKeys[80]=a:190==a.keyCode&&a.altKey?Browser.currentKeys[88]=a:Browser.currentKeys[a.keyCode]=a});window.addEventListener("keyup",function(){Browser.handleKeys()});Object.preventExtensions(Browser)};Browser.runIfInTopFrame(initBrowser)};
