var main,statusText,title,urlHeader,url,linkSwitcher,copiedConfirmation,errorTitle,errorDetails,dismissMessageButton,upgradeButton,dismissDialogButton,tokens,type,noteGuid,userId,premium,baseUrl,origin,sourceUrl,evernoteUrl;
window.addEventListener("DOMContentLoaded",function(){origin="clipper-chrome";SAFARI?origin="clipper-safari":OPERA&&(origin="clipper-opera");main=document.querySelector("#main");statusText=document.querySelector("#status .text");title=document.querySelector("#title");urlHeader=document.querySelector("#urlHeader");url=document.querySelector("#url");linkSwitcher=document.querySelector("#linkSwitcher");copiedConfirmation=document.querySelector("#copiedConfirmation");errorTitle=document.querySelector("#errorTitle span");
errorDetails=document.querySelector("#errorDetails");dismissMessageButton=document.querySelector("#dismissMessage");upgradeButton=document.querySelector("#upgrade");dismissDialogButton=document.querySelector("#dismissDialog");GlobalUtils.localize(document.body);linkSwitcher.addEventListener("click",function(){"source"==linkSwitcher.getAttribute("linkType")?(linkSwitcher.setAttribute("linkType","evernote"),linkSwitcher.innerText=Browser.i18n.getMessage("switchToSourceLink"),url.value=evernoteUrl,urlHeader.innerText=
Browser.i18n.getMessage("evernoteLink")):(linkSwitcher.setAttribute("linkType","source"),linkSwitcher.innerText=Browser.i18n.getMessage("switchToEvernoteLink"),url.value=sourceUrl,urlHeader.innerText=Browser.i18n.getMessage("sourceLink"));Browser.sendToExtension({name:"copyText",text:url.value})});for(var a=document.querySelectorAll(".shareButton"),c=0;c<a.length;c++)a.item(c).addEventListener("click",shareNote);dismissMessageButton.addEventListener("click",function(){document.body.className=document.body.className.replace(/\s*error/g,
"").replace(/\s*nearQuota/g,"");window.parent.postMessage({name:"setShareToolsHeight",height:main.offsetHeight+10},"*")});dismissDialogButton.addEventListener("click",function(){window.parent.postMessage({name:"hideShareTools"},"*")})});Browser.addMessageHandlers({doneSharing:doneSharing,emailResult:emailResult,handleFailure:handleFailure,handleSuccess:doneSharing,receiveClipResultInfo:receiveClipResultInfo});
function doneSharing(a,c,d){if(a.guid&&(noteGuid=a.guid,sourceUrl=a.source,evernoteUrl=a.url,sourceUrl?(url.value=sourceUrl,document.body.className+=" dualLinks",urlHeader.innerText=Browser.i18n.getMessage("sourceLink")):(url.value=evernoteUrl,urlHeader.innerText=Browser.i18n.getMessage("evernoteLink")),document.body.className+=" doneSharing",window.parent.postMessage({name:"setShareToolsHeight",height:main.offsetHeight+10},"*"),c=a.uploaded,d=a.savedAuthInfo,c&&c[userId]&&d&&d.userInfo&&d.userInfo[userId]&&
d.userInfo[userId].quota)){var b=a.shownNearQuotaUpsell;b||(b={});0.75<(c[userId]+a.noteSize)/d.userInfo[userId].quota&&!b[userId]&&(b[userId]=!0,Browser.sendToExtension({name:"setPersistentValue",key:"shownNearQuotaUpsell",value:b}),document.body.className+=" error nearQuota",errorTitle.innerText=Browser.i18n.getMessage("nearQuota"),premium?(errorDetails.innerText=Browser.i18n.getMessage("nearQuotaPremium"),upgradeButton.innerText=Browser.i18n.getMessage("getMoreSpacePremium"),upgradeButton.href=
baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/QuotaCheckout.action?origin="+origin+"&offer=nearQuota")):(errorDetails.innerText=Browser.i18n.getMessage("nearQuotaFree"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=nearQuota")))}}
function emailResult(a,c,d){if(a.error){var b=document.querySelector("#email");b.className+=" error";premium?b.setAttribute("data-error",Browser.i18n.getMessage("emailLimitError",[EDAM_USER_MAIL_LIMIT_DAILY_FREE])):b.setAttribute("data-error",Browser.i18n.getMessage("emailLimitError",[EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM]));setTimeout(function(){b.className=b.className.replace(/\s*error/g,"")},2E3)}}
function handleFailure(a,c,d){document.body.className+=" error";"overQuota"==a.error?(errorTitle.innerText=Browser.i18n.getMessage("cannotSaveClip"),premium?(errorDetails.innerText=Browser.i18n.getMessage("notification_quotaExceededPremium"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/QuotaCheckout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("getMoreSpacePremium")):
(errorDetails.innerText=Browser.i18n.getMessage("notification_quotaExceededFree"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium"))):"noteSizeExceeded"==a.error&&(premium?(document.body.className+=" cannotUpgrade",errorTitle.innerText=Browser.i18n.getMessage("premiumNoteSizeLimit"),errorDetails.innerText=
Browser.i18n.getMessage("noteSizeExceededPremium")):(errorTitle.innerText=Browser.i18n.getMessage("freeNoteSizeLimit"),errorDetails.innerText=Browser.i18n.getMessage("noteSizeExceededFree"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium")));window.parent.postMessage({name:"setShareToolsHeight",
height:main.offsetHeight+10},"*")}
function receiveClipResultInfo(a,c,d){tokens=a.auth;type=a.type;userId=a.userId;premium=a.premium;baseUrl=a.baseUrl;document.body.className=document.body.className.replace(/\s*(doneSharing|dualLinks)/g,"");title.innerText=a.title;32<title.scrollHeight&&(title.className+=" overflow");a.updateGuid&&(statusText.innerText=Browser.i18n.getMessage("updatingClip"));/china/i.test(a.locale)&&(document.body.className+=" china");window.parent.postMessage({name:"setShareToolsHeight",height:main.offsetHeight+
10},"*")}
function shareNote(){if("email"==this.id){var a=tokens.authenticationToken;"biz"==type?a=tokens.bizAuthenticationToken:"linked"==type&&(a=tokens.linked);window.parent.postMessage({name:"showEmailDialog",auth:a,noteGuid:noteGuid,persAuth:tokens.authenticationToken,sharedAuth:"linked"==type?a:null,subject:title.innerText,userId:userId},"*")}else"facebook"==this.id?Browser.sendToExtension({name:"main_openWindow",width:626,height:436,url:"https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(url.value),type:"popup"}):
"twitter"==this.id?Browser.sendToExtension({name:"main_openWindow",width:550,height:420,url:"https://twitter.com/intent/tweet?text="+encodeURIComponent(title.innerText)+"&url="+encodeURIComponent(url.value),type:"popup"}):"linkedin"==this.id?Browser.sendToExtension({name:"main_openWindow",width:520,height:570,url:"http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(url.value)+"&title="+encodeURIComponent(title.innerText),type:"popup"}):"weibo"==this.id&&(a="http://service.weibo.com/share/share.php?url="+
encodeURIComponent(url.value)+"&title="+encodeURIComponent(title.innerText),url.value==evernoteUrl&&(a+="&pic="+encodeURIComponent(url.value+"/thm/note/"+noteGuid)),Browser.sendToExtension({name:"main_openWindow",width:650,height:650,url:a,type:"popup"}))};
