function Auth(w,x){function k(){var a={},b;for(b in e){var d=JSON.parse(JSON.stringify(e[b]));a[b]=d}Persistent.set("savedAuthInfo",{userInfo:a,currentUser:c})}function y(){for(var a=0;a<f.length;a++)l(a,{authenticationToken:null,error:"TIMEOUT"});f=[];g=!1}function l(a,b){try{f[a](b)}catch(d){log.warn("Got error running login callback: "+JSON.stringify(d))}}function z(a){log.warn("failed login: "+a.trace);a=B(a);for(var b=0;b<f.length;b++)l(b,{error:a});f=[];g=!1}function m(a,b){if(g)if(SAFARI?q&&
clearTimeout(q):chrome.alarms.clear("authenticateLongSession"),a)if(a.secondFactorRequired){for(var d=0;d<f.length;d++)l(d,{authenticationToken:a.authenticationToken,secondFactorDeliveryHint:a.secondFactorDeliveryHint,expiration:(new Date).getTime()-a.currentTime+a.expiration});f=[];g=!1}else a.user&&a.user.id&&(n=(new Date).getTime()-a.currentTime,c=a.user.id.toString(),e[c]={},e[c].username=a.user.username,e[c].authenticationToken=a.authenticationToken,e[c].expiration=a.expiration,e[c].premium=
a.user.premiumInfo?a.user.premiumInfo.premium:!1,e[c].shardId=a.user.shardId,e[c].fullName=a.user.name||a.user.username,e[c].email=a.user.email,e[c].quota=a.user.accounting.uploadLimit,e[c].monthEnd=a.user.accounting.uploadLimitEnd,IDB.initAllStores(c,function(){if(a.user.businessUserInfo)e[c].businessId=a.user.businessUserInfo.businessId,h().client.UserStore.authenticateToBusiness(C,a.authenticationToken);else{k();for(var b=0;b<f.length;b++)l(b,{authenticationToken:a.authenticationToken,username:a.user.username,
userId:c,error:!1,premium:a.user.premiumInfo?a.user.premiumInfo.premium:!1,fullName:a.user.name||a.user.username});f=[];g=!1}Browser.runtime.getBackgroundPage(function(a){a.extension.showLoggedInState()})},function(a){log.error(a)}));else z(b)}function C(a,b){if(a){e[c]?(e[c].bizAuthenticationToken=a.authenticationToken,e[c].bizExpiration=a.expiration):log.warn("Got business login for unknown user. Discarding.");k();for(var d=0;d<f.length;d++)l(d,{authenticationToken:e[c].authenticationToken,bizAuthenticationToken:a.authenticationToken,
username:e[c].username,userId:c,error:!1,premium:e[c].premium,fullName:e[c].fullName});f=[];g=!1}else z(b)}function B(a){if(!a)return"UNKNOWN";if("number"===typeof a.code)switch(a.code){case 0:return"NETWORK";case 503:return"HTTP/503"}for(var b=["name","trace"],d=0;d<b.length;d++)if(a[b[d]]){var c=a[b[d]],e=c.match(/errorCode:(\w+)/);if(e)switch(e[1]){case "DATA_REQUIRED":return c.match(/parameter:password/)?"PASSWORD_REQUIRED":c.match(/parameter:username/)?"USERNAME_REQUIRED":"DATA_REQUIRED";case "INVALID_AUTH":return c.match(/parameter:password/)?
"INVALID_PASSWORD":c.match(/parameter:username/)?"INVALID_USERNAME":c.match(/parameter:oneTimeCode/)?"INVALID_TWO_STEP_CODE":"INVALID_AUTH";case "PERMISSION_DENIED":return c.match(/parameter:.*tooManyFailures/)||c.match(/parameter:.*tooManyMessageAttempts/)?"TOO_MANY_FAILURES":c.match(/parameter:.*User.active/)?"ACCOUNT_DEACTIVATED":c.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"PERMISSION_DENIED";case "AUTH_EXPIRED":return c.match(/parameter:password/)?"EXPIRED_PASSWORD":
c.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"AUTH_EXPIRED";case "BAD_DATA_FORMAT":return c.match(/parameter:username/)?"INVALID_USERNAME":"INVALID_AUTH";default:return log.warn("Found unhandled error condition: "+e[1]+c+" while logging in."),"UNKNOWN"}}log.warn("nothing");return"UNKNOWN"}function E(a){if(!a.expiration)return!1;var b=(new Date).getTime(),b=b-n;return b>a.expiration-18E4?!1:!0}function F(a){if(!a.bizExpiration)return!1;var b=(new Date).getTime(),b=b-n;return b>
a.bizExpiration-18E4?!1:!0}function r(a,b){A(a);s(b)}function s(a,b){b||h().client.UserStore.revokeLongSession(function(a,b){b&&log.error("problem revoking auth token: "+b.trace)},e[c].authenticationToken);delete e[c];c="";for(var d in e){c=d;break}k();n=0;if(a)try{a()}catch(D){log.error("Error running logout callback. "+D.stack)}0==Object.keys(e).length&&Browser.runtime.getBackgroundPage(function(a){a.extension.showLoggedOutState()})}function A(a){return e[a]?(c=a,!0):!1}function h(){var a;a=x+t.get("serviceHost")+
"/json";if(u[a])a=u[a];else{var b=new JsonRpc(null,["UserStore.authenticateLongSession","UserStore.authenticateToBusiness","UserStore.revokeLongSession","UserStore.completeTwoFactorAuthentication"],null,x,t.get("serviceHost"),w);b.initWithUrl(a);a=u[a]=b}return a}function v(a){a||(a=c);return(a=e[a])?a:{}}function p(a){if(/macintosh/i.test(a))a="MacOS";else if(/windows/i.test(a))if(a=a.match(/Windows NT (.+);/))switch(a[1]){case "3.1":a="Windows NT 3.1";break;case "3.5":a="Windows NT 3.5";break;case "3.51":a=
"Windows NT 3.51";break;case "4.0":a="Windows NT 4.0";break;case "5.0":a="Windows 2000";break;case "5.1":a="Windows XP";break;case "5.2":a="Windows XP";break;case "6.0":a="Windows Vista";break;case "6.1":a="Windows 7";break;case "6.2":a="Windows 8";break;default:a="Windows"}else a="Windows";else a=/linux/i.test(a)?"Linux":"Unknown Operating System";return SAFARI?"Safari ("+a+")":OPERA?"Opera ("+a+")":"Google Chrome ("+a+")"}var t=new BootstrapInfo(w);t.get("serviceHost");var u={},e={},c=null,n=0,
f=[],q=0,g=!1;(function(){var a=Persistent.get("savedAuthInfo");e={};c="";if(a&&a.currentUser&&a.userInfo){c=a.currentUser;for(var b in a.userInfo)try{e[b]=a.userInfo[b]}catch(d){log.warn("Couldn't restore credentials for user "+b)}if(!e[c])for(b in log.warn("No entry for saved user, picking another."),e){currentuser=b;k();break}}else Persistent.set("savedAuthInfo",{})})();this.getAuthTokens=function(a){var b=v();if(b.authenticationToken){var d={authenticationToken:b.authenticationToken};b.bizAuthenticationToken?
new Date+18E4>b.bizExpiration?h().client.UserStore.authenticateToBusiness(function(b,f){b?(e[c].bizAuthenticationToken=b.authenticationToken,e[c].bizExpiration=b.expiration,k(),d.bizAuthenticationToken=b.authenticationToken,a(d)):(log.error("problem refreshing business token: "+f.trace),f.trace&&r(c,function(){a(null)}))},b.authenticationToken):(d.bizAuthenticationToken=b.bizAuthenticationToken,a(d)):a(d)}else a(null)};this.isAuthenticated=function(a){function b(b,d){b?(e[c].bizAuthenticationToken=
b.authenticationToken,e[c].bizExpiration=b.expiration,k(),f.bizAuthenticationToken=b.authenticationToken,f.bizExpiration=b.expiration,a(f)):(log.error("problem refreshing business auth token: "+d.trace),d.trace&&r(c,function(){a(null)}))}var d=v();if(d.authenticationToken&&E(d)){var f={username:d.username,authenticationToken:d.authenticationToken,userId:c,shardId:d.shardId,premium:d.premium,fullName:d.fullName};d.bizAuthenticationToken?(f.businessId=d.businessId,F(d)?(f.bizAuthenticationToken=d.bizAuthenticationToken,
f.bizExpiration=d.bizExpiration,a(f)):h().client.UserStore.authenticateToBusiness(b,d.authenticationToken)):a(f)}else a(null)};this.login=function(a,b,c){c&&f.push(c);g||(g=!0,SAFARI?h().client.UserStore.authenticateLongSession(m,a,b,"en-safari-clipper-xauth-new","1fbffc8cf53bd605",Persistent.get("deviceID"),p(navigator.userAgent),!0):OPERA?h().client.UserStore.authenticateLongSession(m,a,b,"en-opera-clipper-xauth-new","bda9ae45efd276dc",Persistent.get("deviceID"),p(navigator.userAgent),!0):h().client.UserStore.authenticateLongSession(m,
a,b,"en-chrome-clipper-xauth-new","57542b7c39ab82e9",Persistent.get("deviceID"),p(navigator.userAgent),!0),SAFARI?q=setTimeout(y,3E4):(chrome.alarms.onAlarm.addListener(function(a){"authenticateLongSession"==a.name&&y()}),chrome.alarms.create("authenticateLongSession",{when:Date.now()+3E4})))};this.logout=s;this.logoutUser=r;this.logoutAll=function(){for(;c;)s(null)};this.getCurrentUser=function(){return c};this.getUserInfo=v;this.getLoggedInUserIds=function(){var a=[],b;for(b in e)a.push(b);a.sort(function(a,
b){e[a].username.toLowerCase();e[b].username.toLowerCase();return a<b?-1:a>b?1:0});return a};this.setCurrentUser=A;this.completeTwoFactorAuthentication=function(a,b,c){c&&f.push(c);g||(g=!0,h().client.UserStore.completeTwoFactorAuthentication(m,a,b,Persistent.get("deviceID"),p(navigator.userAgent)))};Object.preventExtensions(this)}Object.preventExtensions(Auth);
