var IDB={};
(function(){function l(c,a,f,e){if(f[a]){var d=c.put(f[a],f[a].guid||a);d.onsuccess=function(){l(c,a+1,f)};d.onerror=e;d.onblocked=e}}function m(c,a,f,e,d){if(f[a]){var b=c.delete(f[a]);b.onsuccess=function(){m(c,a+1,f,e,d)};b.onerror=d;b.onblocked=d}else e()}var h={};IDB.setGroup=function(c,a,f,e){if(h[c]){var d=h[c].transaction([a],"readwrite").objectStore(a);d.clear().onsuccess=function(){l(d,0,f,e)}}else{var b=indexedDB.open(c,1);b.onsuccess=function(d){h[c]=d.target.result;var b=h[c].transaction([a],"readwrite").objectStore(a);
b.clear().onsuccess=function(){l(b,0,f,e)}};b.onerror=function(a){e&&e("idb error setting group: "+JSON.stringify(a.target.error))};b.onblocked=function(a){e&&e("idb blocked setting group: "+JSON.stringify(a.target.error))}}};IDB.set=function(c,a,f,e,d,b){if(h[c]){var g=h[c].transaction([a],"readwrite").objectStore(a).put(e,f);d&&(g.onsuccess=d)}else g=indexedDB.open(c,1),g.onsuccess=function(b){h[c]=b.target.result;b=h[c].transaction([a],"readwrite").objectStore(a).put(e,f);d&&(b.onsuccess=d)},g.onerror=
function(a){b&&b("idb error setting: "+JSON.stringify(a.target.error))},g.onblocked=function(a){b&&b("idb blocked setting: "+JSON.stringify(a.target.error))}};IDB.get=function(c,a,f,e,d){if(h[c])h[c].transaction([a]).objectStore(a).get(f).onsuccess=function(a){e(a.target.result?a.target.result:null)};else{var b=indexedDB.open(c,1);b.onsuccess=function(b){h[c]=b.target.result;h[c].transaction([a]).objectStore(a).get(f).onsuccess=function(a){e(a.target.result?a.target.result:null)}};b.onerror=function(a){d&&
d("idb error getting: "+JSON.stringify(a.target.error))};b.onblocked=function(a){d&&d("idb blocked getting: "+JSON.stringify(a.target.error))}}};IDB.getGroup=function(c,a,f,e,d,b){if(h[c]){var g=[];e?f?h[c].transaction([a]).objectStore(a).index(f).openCursor(e).onsuccess=function(a){a.target.result?(g.push(a.target.result.value),a.target.result.continue()):d(0<g.length?g:null)}:h[c].transaction([a]).objectStore(a).openCursor(e).onsuccess=function(a){a.target.result?(g.push(a.target.result.value),
a.target.result.continue()):d(0<g.length?g:null)}:h[c].transaction([a]).objectStore(a).openCursor().onsuccess=function(a){a.target.result?(g.push(a.target.result.value),a.target.result.continue()):d(0<g.length?g:null)}}else{var k=indexedDB.open(c,1);k.onsuccess=function(b){h[c]=b.target.result;var g=[];e?f?h[c].transaction([a]).objectStore(a).index(f).openCursor(e).onsuccess=function(a){a.target.result?(g.push(a.target.result.value),a.target.result.continue()):d(0<g.length?g:null)}:h[c].transaction([a]).objectStore(a).openCursor(e).onsuccess=
function(a){a.target.result?(g.push(a.target.result.value),a.target.result.continue()):d(0<g.length?g:null)}:h[c].transaction([a]).objectStore(a).openCursor().onsuccess=function(a){a.target.result?(g.push(a.target.result.value),a.target.result.continue()):d(0<g.length?g:null)}};k.onerror=function(a){b&&b("idb error getting group: "+JSON.stringify(a.target.error))};k.onblocked=function(a){b&&b("idb blocked getting group: "+JSON.stringify(a.target.error))}}};IDB.deleteGroup=function(c,a,f,e,d,b){if(h[c]){var g=
[];h[c].transaction([a]).objectStore(a).index(f).openCursor(e).onsuccess=function(e){e.target.result?(g.push(e.target.result.primaryKey),e.target.result.continue()):m(h[c].transaction([a],"readwrite").objectStore(a),0,g,d,b)}}else{var k=indexedDB.open(c,1);k.onsuccess=function(g){h[c]=g.target.result;var k=[];h[c].transaction([a]).objectStore(a).index(f).openCursor(e).onsuccess=function(e){e.target.result?(k.push(e.target.result.primaryKey),e.target.result.continue()):m(h[c].transaction([a],"readwrite").objectStore(a),
0,k,d,b)}};k.onerror=function(a){b&&b("idb error deleting group: "+JSON.stringify(a.target.error))};k.onblocked=function(a){b&&b("idb blocked deleting group: "+JSON.stringify(a.target.error))}}};IDB.initAllStores=function(c,a,f){var e=indexedDB.open(c,1);e.onsuccess=function(d){h[c]=d.target.result;!e.upgraded&&a&&a()};e.onupgradeneeded=function(d){for(var b=d.target.result.objectStoreNames,c=0;c<b.length;c++)d.target.result.deleteObjectStore(b[c]);b=d.target.result.createObjectStore("notebooks");
b.createIndex("stack","stack",{unique:!1});b=d.target.result.createObjectStore("sharedNotebooks");b.createIndex("stack","stack",{unique:!1});d.target.result.createObjectStore("tags");d.target.result.createObjectStore("bizTags");b=d.target.result.createObjectStore("pers_filRec");b.createIndex("timestamp","timestamp",{unique:!1});b=d.target.result.createObjectStore("biz_filRec");b.createIndex("timestamp","timestamp",{unique:!1});b=d.target.result.createObjectStore("pers_simSearch");b.createIndex("timestamp",
"timestamp",{unique:!1});b=d.target.result.createObjectStore("biz_simSearch");b.createIndex("timestamp","timestamp",{unique:!1});e.upgraded=!0;a&&a()};e.onerror=function(a){f&&f("Failed to connect to IndexedDB: "+JSON.stringify(a.target.error))};e.onblocked=function(a){f&&f("Failed to connect to IndexedDB: "+JSON.stringify(a.target.error))}}})();Object.preventExtensions(IDB);
